name: Test NookNote

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  APP_NAME: NookNote

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
        
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: '5.9'
        
    - name: Cache Swift dependencies
      uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('Package.swift') }}
        restore-keys: |
          ${{ runner.os }}-spm-
          
    - name: Run tests
      run: |
        echo "🧪 Running Swift tests..."
        swift test
        
    - name: Build debug
      run: |
        echo "🔨 Building debug version..."
        swift build --configuration debug
        
    - name: Build release
      run: |
        echo "🔨 Building release version..."
        swift build --configuration release
        
    - name: Verify build outputs
      run: |
        echo "🔍 Verifying build outputs..."
        
        # Check debug build
        if [ ! -f ".build/debug/$APP_NAME" ]; then
          echo "❌ Debug build failed"
          exit 1
        fi
        
        # Check release build
        if [ ! -f ".build/release/$APP_NAME" ]; then
          echo "❌ Release build failed"
          exit 1
        fi
        
        echo "✅ Both debug and release builds successful"
        
    - name: Run static analysis
      run: |
        echo "🔍 Running static analysis..."
        
        # Check for common Swift issues
        echo "Checking for TODO/FIXME comments..."
        find Sources -name "*.swift" -exec grep -Hn "TODO\|FIXME" {} \; || true
        
        echo "Checking for force unwraps..."
        find Sources -name "*.swift" -exec grep -Hn "!" {} \; | grep -v "// swiftlint" || true
        
        echo "✅ Static analysis complete"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: test-build-${{ github.sha }}
        path: |
          .build/debug/${{ env.APP_NAME }}
          .build/release/${{ env.APP_NAME }}
        retention-days: 7